services:
  redis:
    image: redis:7-alpine
    container_name: rss-skull-redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 8.8.4.4
    # ports:
    #   - "6380:6379"  # Removido para evitar conflitos
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  rss-skull-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rss-skull-bot
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 8.8.4.4
    ports:
      - "8916:8916"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=file:/app/data/production.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8916
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      - app_data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8916/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  app_data:
    driver: local