services:
  redis:
    image: redis:7-alpine
    container_name: rss-skull-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # RSS-Bridge disabled for now - requires cookies/session management
  # rss-bridge:
  #   image: rssbridge/rss-bridge:latest
  #   container_name: rss-bridge
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./rss-bridge/config:/config
  #   environment:
  #     - INSTAGRAM_SESSION_ID=${INSTAGRAM_SESSION_ID}
  #     - INSTAGRAM_DS_USER_ID=${INSTAGRAM_DS_USER_ID}
  #   restart: unless-stopped

  rss-skull-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: rss-skull-bot
    ports:
      - "8916:8916"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=file:/app/data/production.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8916
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      # Reddit OAuth API credentials
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      # - RSS_BRIDGE_HOST=http://rss-bridge:80  # Disabled
    volumes:
      - app_data:/app/data
      - backups_data:/app/backups
    depends_on:
      redis:
        condition: service_healthy
      # rss-bridge:  # Disabled
      #   condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8916/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local
  app_data:
    driver: local
  backups_data:
    driver: local

# IMPORTANT: Database persistence is now properly configured!
#
# For clean deployment (removes all data):
# docker-compose down -v && docker-compose up -d --build
#
# For updates preserving data (RECOMMENDED):
# docker-compose up -d --build
#
# The database will persist between container restarts thanks to:
# - Volume mount: app_data:/app/data
# - Backup mount: ./backups:/app/backups
# - Fixed Dockerfile CMD (no more data deletion)