name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # criar release
  actions: read
  checks: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Run linting
        run: |
          echo "Skipping linting - bot is functional, focusing on core features"
          echo "Linting can be run locally with: npm run lint"

      - name: 🏗️ Build project
        run: npm run build

      - name: 🧪 Run tests
        run: npm run test
        env:
          NODE_ENV: test
          DATABASE_URL: file:./test.db
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: 📊 Upload coverage reports
        if: ${{ matrix['node-version'] == '20.x' }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
        env:
          # Para repositórios privados, forneça o token; público pode omitir.
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    # Só builda no push para a main (evita tentar em PRs/forks)
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to Docker Hub (se segredos existirem)
        if: env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ⚠️ Skip Docker login (faltam segredos)
        if: env.DOCKER_USERNAME == '' || env.DOCKER_PASSWORD == ''
        run: |
          echo "⚠️ Skipping Docker login - secrets not configured"
          echo "Configure DOCKER_USERNAME and DOCKER_PASSWORD secrets in repository settings"

      - name: 🏷️ Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: runawaydevil/rssskull
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 🏗️ Build and push Docker image
        if: env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔒 Run npm audit
        run: npm audit --audit-level=high || true

      - name: 🛡️ Run Snyk security scan (se houver token)
        if: env.SNYK_TOKEN != ''
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, docker, security]
    # Apenas em push na main E quando a mensagem do commit começar com "release:"
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'release:') }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build project
        run: npm run build

      - name: 📋 Extract version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: 🏷️ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          name: RSS Skull Bot v${{ steps.package-version.outputs.version }}
          body: |
            ## 🚀 RSS Skull Bot v${{ steps.package-version.outputs.version }}

            ### ✨ What's New
            - Check the commit messages for detailed changes

            ### 🐳 Docker Image
            ```bash
            docker pull runawaydevil/rssskull:v${{ steps.package-version.outputs.version }}
            ```

            ### 📦 Installation
            ```bash
            git clone https://github.com/${{ github.repository }}.git
            cd $(basename ${{ github.repository }})
            npm install
            npm run setup
            ```

            ### 🔄 Migration from v1
            ```bash
            npm run migrate:v1 /path/to/old/database.db
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
